[package]
name = "typegen"
version = "0.0.0"
authors = ["Redglyph <redglyph@gmail.com>"]
description = "A `cargo generate` template for quick-starting a procedural macro crate"
keywords = ["template", "proc_macro", "procmacro"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.23"
proc-macro2 = "1.0.51"
syn = { version = "1.0.107", features = ["full", "fold", "visit-mut", "derive"] }
proc-macro-error = "1"

[dev-dependencies]
num = "0"
