[package]
name = "trait-gen"
description = "Trait implementation generator macro"
version = "0.1.7"
edition = "2021"
authors = ["Redglyph"]
categories = ["rust-patterns"]
keywords = ["proc-macro", "macro", "trait", "generator"]
documentation = "https://docs.rs/trait-gen"
homepage = "https://github.com/blueglyph/trait_gen"
license = "MIT"
repository = "https://github.com/blueglyph/trait_gen"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = { version = "1", features = ["span-locations"] }
syn = { version = "1", features = ["full", "visit-mut", "extra-traits"] }
proc-macro-error = "1"

[dev-dependencies]
